# Generated by Django 2.0.1 on 2018-02-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0002_auto_20180213_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetype',
            old_name='fileType',
            new_name='fileTypeName',
        ),
    ]
