# Generated by Django 2.0.1 on 2018-02-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NasaFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('numOfDownloads', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(unique=True, upload_to='')),
            ],
        ),
    ]
