# Generated by Django 2.0.1 on 2018-02-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileType', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='nasafiles',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='nasafiles',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='nasafiles',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nasafiles',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebPage.FileType'),
        ),
    ]
